name: weather_pipeline
version: "1.0.0"
config-version: 2

profile: weather_pipeline

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_pipeline:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
